language: android

jdk:
  - oraclejdk8

android:
  components:
    - tools
    - build-tools-25.0.2
    - android-23
    - platform-tools
    - extra-android-support
    - extra-android-m2repository

branches:
  except:
    - gh-pages

# Disable Travis container-based infrastructure to correct
# resource consumption in gradle presumably due to dexing.
sudo: true
